### ISSUE TITLE
Missing API function: hipMemcpyToSymbol(const T& symbol, ...)

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm-Developer-Tools/HIP-CPU#12]
While it is [undocumented](https://rocmdocs.amd.com/en/latest/ROCm_API_References/HIP_API/Memory-Management.html?highlight=hipMemcpyToSymbol#hipmemcpytosymbol), `hip_runtime_api.h` has an [overload](https://github.com/ROCm-Developer-Tools/HIP/blob/develop/include/hip/hcc_detail/hip_runtime_api.h#L3843-L3848) to `hipMemcpyToSymbol` that takes a reference to a variable, instead of a pointer to one (or it's name). This is likely a facilty to not have to use the [`HIP_SYMBOL`](https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-porting-guide.html?highlight=HIP_SYMBOL#memcpytosymbol) which does nothing, just prepends the addressof operator (but only for the [nvcc back-end](https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/include/hip/nvcc_detail/hip_runtime.h#L96), the macro for the HCC/AMD back-end just [repeats the var name verbatim](https://github.com/ROCm-Developer-Tools/HIP/blob/2080cc113a2d767352b512b9d24c0620b6dee790/include/hip/hcc_detail/hip_runtime.h#L334), effectively relaying to the missing API function.)

We came across this issue while porting user code to using HIP-CPU.

**Comment by AlexVlx** [comment]
https://github.com/ROCm-Developer-Tools/HIP-CPU/commit/3886b0f32f152e784f5089e9e7e54a6444d91da9 should address this, please re-open if that is not the case.
