### ISSUE TITLE
libco #defines conflict with Qt

### ISSUE THREAD

**Issue by franjesus** [ROCm-Developer-Tools/HIP-CPU#15]
These 2 symbols are colliding, is there a "nice" way to put libco in its own namespace? (I guess not since it's C89)
```
/opt/HIP-CPU/external/libco/settings.h:99: note: macro "section" defined here
   99 |   #define section(name) __attribute__((section(#name)))
      |
In file included from /opt/Qt/5.12.6/gcc_64/include/QtCore/QString:1,
                 from ../modules/Writer.cpp:13:
/opt/Qt/5.12.6/gcc_64/include/QtCore/qstring.h:376:104: error: macro "section" passed 4 arguments, but takes just 1
  376 |     QString section(const QString &in_sep, int start, int end = -1, SectionFlags flags = SectionDefault) const;
```

**Comment by AlexVlx** [comment]
Thank you for filing this. Since that's a macro, namespacing won't really help much. Also, we're clients of libco so modifying it would be a last resort (although possibly desirable, ultimately). What I think can be done is something like this:
```cpp
#if defined(section)
#undef section
#endif
#include <whatever_qt_file_leads_to_qstring.h_being_included>
```

**Comment by franjesus** [comment]
Hi Alex,

how about 
```cpp
#include "../../../../external/libco/libco.h"
#undef section
```
in fiber.hpp:24 ?

Works for me :)

**Comment by AlexVlx** [comment]
@franjesus yup, that works too and is cleaner, but I've convinced myself that having a macro squat on such a common name is a faux pas, so I'll bite the bullet and just rename the macro to `LIBCO_SECTION` (other libco macros are similarly "namespaced", to it should be possible to have this upstreamed eventually).

**Comment by franjesus** [comment]
Thanks! makes sense
