### ISSUE TITLE
Clang on Windows: 't' cannot be thread local when declared 'dllexport'

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm-Developer-Tools/HIP-CPU#20]
Trying to use HIP-CPU on Windows using Clang results in a compiler error:
```
deps/hip-cpu/include\hip/../../src/include/hip/detail/runtime.hpp:180:55: error: 't' cannot be thread local when declared 'dllexport'
                static thread_local std::vector<Task> t;
                                                      ^
```
Note to "self": change `hip/hip_defines.h` from
```
#if defined(_WIN32)
```
to
```
#if defined(_WIN32) && (!defined(__clang__))
```
solves this issue. Likely a more sophisticated mechanism will be needed instead of this hotfix.

**Comment by AlexVlx** [comment]
Should be fixed by https://github.com/ROCm-Developer-Tools/HIP-CPU/commit/e98cd3cc09b212d58e5fd4afaeb6e70f74638ab3. Thank you for reporting it.
