### ISSUE TITLE
Missing API function: hipMallocPitch & hipMemcpy2D

### ISSUE THREAD

**Issue by ueqri** [ROCm-Developer-Tools/HIP-CPU#23]
According to [HIP API docs](https://rocm-developer-tools.github.io/HIP/group__Memory.html), `hipMallocPitch` and related `hipMemcpy2D` are fully supported by HIP. 

But when I build the HIP codes with HIP-CPU, the errors occur on `hipMallocPitch` and `hipMemcpy2D`, which are not declared in HIP-CPU runtime library.

The minimal code is here:
```c++
#include <hip/hip_runtime_api.h>

int main()
{
  int row = 10, col = 10;
  float h_ptr[row][col];
  float *d_ptr;
  size_t pitch;

  hipMallocPitch(&d_ptr, &pitch, col*sizeof(float), row);
  hipMemcpy2D(d_ptr, pitch, h_ptr, col*sizeof(float), col*sizeof(float), row, hipMemcpyHostToDevice);

  return 0;
}
```

After looking through the [src/include/hip/detail/api.hpp](https://github.com/ROCm-Developer-Tools/HIP-CPU/blob/master/src/include/hip/detail/api.hpp) & [include/hip/hip_api.h](https://github.com/ROCm-Developer-Tools/HIP-CPU/blob/master/include/hip/hip_api.h), I found `hipMemcpy2DAsync` is the only implemented function related to the problem.

Since we could use the trivial way to implement those pitched memory in CPU simulation, could we just add the wrap for `hipMallocPitch` and `hipMemcpy2D` in HIP-CPU to avoid compiler errors? I'd be glad to contribute for this.

**Comment by AlexVlx** [comment]
Thank you for the patch!
