### ISSUE TITLE
Missing some warp cross lane functions

### ISSUE THREAD

**Issue by ueqri** [ROCm-Developer-Tools/HIP-CPU#25]
According to HIP programming guides, [Warp Cross Lane Functions](https://rocmdocs.amd.com/en/latest/Programming_Guides/HIP-GUIDE.html#warp-cross-lane-functions) are well supported in HIP. But I couldn't build the HIP code with some of these wrap functions e.g. `int __all(int predicate)` and `int __any(int predicate)` using HIP-CPU library.

Since those APIs are widely used in warp-level programing, I was wondering if there are some plans for these functions, `__all` and `__any` (`__ballot` is already implemented in HIP-CPU).

**Comment by AlexVlx** [comment]
Thank you for filing this @ueqri . I will add them, but please note that there's a caveat with Cross Lane Functions (it's one of the divergence points between CPU and GPU), in that on CPU these'll carry barrier semantics (as if calling `__syncthreads`). I think that @MathiasMagnus ran into it, so he might have something to add.

**Comment by AlexVlx** [comment]
Fixed (modulo lack of lockstep behaviour).
