### ISSUE TITLE
Is it possible to build MIOpen on HIP-CPU?

### ISSUE THREAD

**Issue by xlindo** [ROCm-Developer-Tools/HIP-CPU#35]
Hi all,

does anyone try on this target in order to run tensorflow etc. on HIP-CPU?

**Comment by AlexVlx** [comment]
Hello, thank you for your question. MIOpen is a highly optimised, architecture specific library. Thus, unless upstream decides to add support for CPU targets, it is not going to be usable with HIP-CPU. However, HIP-CPU composes with libraries that offer similar functionality for the CPU, such as <https://github.com/amd/ZenDNN> or <https://github.com/oneapi-src/oneDNN>, which would give you the capability you are looking for. I am going to close this but feel free to re-open if more info is forthcoming.
